// Code generated by sqlc. DO NOT EDIT.

import { Sql } from "postgres";

export const getAuthorQuery = `-- name: GetAuthor :one
SELECT id, name, status, required_status, bio FROM authors
WHERE id = $1 LIMIT 1`;

export interface GetAuthorArgs {
    id: string;
}

export type PublicAuthorStatus = "draft" | "published" | "deleted";

export interface GetAuthorRow {
    id: string;
    name: string;
    status: PublicAuthorStatus | null;
    requiredStatus: PublicAuthorStatus;
    bio: string | null;
}

export async function getAuthor(sql: Sql, args: GetAuthorArgs): Promise<GetAuthorRow | null> {
    const rows = await sql.unsafe(getAuthorQuery, [args.id]).values();
    if (rows.length !== 1) {
        return null;
    }
    const row = rows[0];
    if (!row) {
        return null;
    }
    return {
        id: row[0],
        name: row[1],
        status: row[2],
        requiredStatus: row[3],
        bio: row[4]
    };
}

export const listAuthorsQuery = `-- name: ListAuthors :many
SELECT id, name, status, required_status, bio FROM authors
ORDER BY name`;

export interface ListAuthorsRow {
    id: string;
    name: string;
    status: PublicAuthorStatus | null;
    requiredStatus: PublicAuthorStatus;
    bio: string | null;
}

export async function listAuthors(sql: Sql): Promise<ListAuthorsRow[]> {
    return (await sql.unsafe(listAuthorsQuery, []).values()).map(row => ({
        id: row[0],
        name: row[1],
        status: row[2],
        requiredStatus: row[3],
        bio: row[4]
    }));
}

export const createAuthorQuery = `-- name: CreateAuthor :one
INSERT INTO authors (
  name, bio, status, required_status
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, status, required_status, bio`;

export interface CreateAuthorArgs {
    name: string;
    bio: string | null;
    status: string | null;
    requiredStatus: string;
}

export interface CreateAuthorRow {
    id: string;
    name: string;
    status: PublicAuthorStatus | null;
    requiredStatus: PublicAuthorStatus;
    bio: string | null;
}

export async function createAuthor(sql: Sql, args: CreateAuthorArgs): Promise<CreateAuthorRow | null> {
    const rows = await sql.unsafe(createAuthorQuery, [args.name, args.bio, args.status, args.requiredStatus]).values();
    if (rows.length !== 1) {
        return null;
    }
    const row = rows[0];
    if (!row) {
        return null;
    }
    return {
        id: row[0],
        name: row[1],
        status: row[2],
        requiredStatus: row[3],
        bio: row[4]
    };
}

export const deleteAuthorQuery = `-- name: DeleteAuthor :exec
DELETE FROM authors
WHERE id = $1`;

export interface DeleteAuthorArgs {
    id: string;
}

export async function deleteAuthor(sql: Sql, args: DeleteAuthorArgs): Promise<void> {
    await sql.unsafe(deleteAuthorQuery, [args.id]);
}

export default function makeQueries(db: Parameters<typeof getAuthor>[0]) {
    return {
        getAuthor: (args: GetAuthorArgs) => getAuthor(db, args),
        listAuthors: () => listAuthors(db),
        createAuthor: (args: CreateAuthorArgs) => createAuthor(db, args),
        deleteAuthor: (args: DeleteAuthorArgs) => deleteAuthor(db, args)
    };
}

